site_name: Ashok Kumar Chaudhary
site_url: https://ashok-ga.github.io/
repo_url: https://github.com/ashok-ga/ashok-ga.github.io
repo_name: ashok-ga/ashok-ga.github.io

theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - navigation.expand
    - navigation.instant
    - search.suggest
    - content.code.copy

nav:
  - Home: index.md
  - Projects: projects.md
  - Resume: resume.md
  - Blog: blog.md
  - Contact: contact.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite

extra_css: []
extra_javascript: []
